bitpodio/bitpodjs

api/callback.js
nuxt.config.js

Updated configuration to resolve login issues when site is hosted on a sub path.

Site sub path configuration

---

components/common/form/date.vue
components/common/form/timezone/index.vue
components/common/form/timezone/timezone-list.js
components/common/grid/index.vue
config/apps/event/content.js
config/common/templates/grid/actions/grid/new-item.vue
nuxt.config.js
package.json
plugins/date-time-picker.js
utility/form.js
yarn.lock

add timezone & date time component

Feat form controls

---

components/common/form/checkbox.vue
components/common/form/date.vue
components/common/form/file.vue
components/common/form/lookup.vue
components/common/form/timezone/index.vue
components/common/grid/index.vue
config/apps/event/content.js
config/common/templates/grid/actions/grid/new-item.vue
config/common/templates/grid/actions/row-select/edit-item.vue
utility/form.js

1. form validation (rules) for all vuetify controls
2. default value for control
3. Multiple value in lookup

Feat multiple value lookup

---

components/common/form/lookup.vue
config/apps/event/content.js
config/apps/event/gql/registrationList.gql
config/apps/event/rest/index.js
config/common/templates/grid/actions/grid/new-item.vue
config/common/templates/grid/actions/row-select/edit-item.vue
config/templates/grids/registration-grid/column-0.vue
utility/form.js
utility/object.js

1. add REST for lookup
2. embed field for new, edit record

feat: add REST for lookup & embed field for new, edit record

---

components/common/form/checkbox.vue
components/common/form/date.vue
components/common/form/file.vue
components/common/form/lookup.vue
components/common/form/text-field.vue
components/common/form/timezone/index.vue
config/apps/event/content.js
utility/form-control.js
utility/form.js

1. add form field label
2. add display order for form field
` 
> EventName: {
displayOrder: 6,
caption: 'Event Name',
form: {
caption: 'EventName *',
displayOrder: 4,
},
searchEnable: true
}
`

feat: add form field label & display order

---

assets/styles/main.css
components/common/grid/index.vue
config/apps/event/content.js
layouts/admin.vue
layouts/default.vue
layouts/event.vue
layouts/logoutlayout.vue
nuxt.config.js
pages/index.vue
utility/index.js

#Mobile Fixes
#Login Box with Mobile UI

Feat ui fixes

---

config/apps/event/gql/event.gql
config/apps/event/gql/templateList.gql
pages/apps/_app/event/_id/editEventSetting.vue
pages/apps/_app/event/_id/editSiteSetting.vue

Added the registration settings form

Feat registration settings form

---

api/index.js
components/common/organization-list/organization-list.vue
layouts/event.vue
store/index.js

1. fetch current org data based on request host
2. add org list in popup, where user can select org and open it in new tab
current org details can be accessed using 
this.$store.state.currentOrg
like current org id => this.$store.state.currentOrg.id

Fetch current org and org list popup

---

components/common/form/date.vue
components/common/form/lookup.vue
components/common/grid/index.vue
config/apps/event/content.js
config/common/templates/grid/actions/grid/index.vue
config/common/templates/grid/actions/grid/new-item.vue
config/common/templates/grid/actions/row-select/delete-item.vue
config/common/templates/grid/actions/row-select/edit-item.vue
config/common/templates/grid/actions/row-select/index.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue
utility/form.js
utility/index.js

1. add context props for grid & its forms
2. itemTitle to new,edit form
"itemTitle" field added to view for adding title to new,edit forms
`
>views: {
Registrations: {
itemTitle: 'Registration',
title: 'Registrations',
type: 'list',
}
}
`
3. add computed for lookup data
4. new form Mutation object fix
5. add onChange prop for Lookup & date

Add context props to grid forms & computed for lookup

---

assets/styles/main.css
config/templates/grids/discount-grid/actions/row-select/make-copy.vue
config/templates/grids/eventInvites-grid/actions/grid/new-item.vue
config/templates/grids/eventRegistrationQuestion-grid/actions/grid/new-item.vue
config/templates/grids/eventRegistrationQuestion-grid/actions/row-select/edit-item.vue
config/templates/grids/link-grid/actions/grid/new-item1.vue
nuxt.config.js
pages/flat/forms.vue
pages/flat/stepforms.vue

Feat send invite form

---

components/common/form/lookup.vue
components/common/form/tags.vue
config/common/templates/grid/actions/grid/new-item.vue
nuxt.config.js
plugins/v-datetime-picker.js
utility/form.js

1. add tag control
2. new item refresh issue

Bug new item refresh data

---

pages/apps/_app/event/_id/editEventForm.vue
pages/apps/_app/event/_id/editEventSetting.vue
pages/apps/_app/event/_id/editSeoForm.vue
pages/apps/_app/event/_id/editSiteSetting.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue

Added the recurring event form seo details form and event settings form

Feat edit recurring event form

---

pages/apps/_app/event/recurring/_id/index.vue

bug_recurring_event:fixed the naming convention

---

components/common/form/datetime-picker.vue
package.json
plugins/v-datetime-picker.js
yarn.lock

add date-time-picker as a global component

Bug datetime picker

---

components/common/copy/index.vue
components/common/form/file.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/organization/_id/index.vue

Added the image upload functionality

Feat image gallery upload

---

config/apps/event/gql/eventRegistrationTicketSlot.gql
config/apps/event/gql/ticket.gql
pages/apps/_app/registration/_id/cancelRegistration.vue
pages/apps/_app/registration/_id/editRegistration.vue
pages/apps/_app/registration/_id/index.vue
pages/apps/_app/registration/_id/refundRegistration.vue
strings.js

Edit Registration, Cancel Registration and Refund functionality

Feat registration actions

---

components/common/grid/index.vue
config/apps/event/content.js
config/common/templates/grid/actions/grid/index.vue
config/common/templates/grid/actions/row-select/index.vue
utility/form.js
utility/object.js

1. add config to hide grid & row-select action
2. grid column filename changed to lower case

Feat template file name

---

components/common/grid/index.vue
config/apps/event/content/registrations.js
config/common/templates/grid/actions/grid/new-item.vue
config/common/templates/grid/actions/row-select/delete-item.vue
config/common/templates/grid/actions/row-select/edit-item.vue
nuxt.config.js
utility/form.js

1. hide pagination for less records
2. caption for default grid action( new, edit, delete)

Hide pagination for less records

---

components/common/form/file.vue
components/common/grid/index.vue
config/apps/admin/content/badge.js
config/apps/admin/content/index.js
config/apps/admin/content/lookup.js
config/apps/admin/content/marketingtemplates.js
config/apps/admin/content/organization.js
config/apps/admin/content/registrationformdetails.js
config/apps/admin/content/users.js
config/apps/admin/gql/businessUnit.gql
config/apps/admin/gql/roles.gql
config/templates/grids/accessKey-grid/column-expiresat.vue
config/templates/grids/organizationBussinessUnit-grid/column-default.vue
config/templates/grids/registrationform-grid/column-isattendeefield.vue
config/templates/grids/registrationform-grid/column-isrequired.vue
config/templates/grids/registrationform-grid/column-isshowfield.vue
config/templates/grids/userRoles-grid/column-rolemappings.vue

Added Default forms for admin
Column templates for grids
Default form changes

Feat actions administration

---

assets/styles/main.css
config/templates/grids/badge-grid/body.vue

Feat csslintfix

---

assets/styles/main.css
components/common/viewDropdown/index.vue
components/newSingleEvent.vue
config/templates/grids/badge-grid/body.vue
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
config/templates/grids/invitetemplate-grid/body.vue
config/templates/grids/livedraft-grid/body.vue
config/templates/grids/seatmap-grid/body.vue
nuxt.config.js
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue
pages/apps/_app/eventboard/index.vue
pages/apps/_app/organization/_id/index.vue

:bug: ui fixes v3

---

config/templates/grids/livedraft-grid/body.vue
pages/apps/_app/event/_id/editEventForm.vue

Added the edit form in the draft tiles section

Tile edit event form

---

components/common/copy/index.vue
config/apps/admin/content/accesskey.js
config/templates/grids/accessKey-grid/actions/grid/new-item.vue
config/templates/grids/accessKey-grid/column-3.vue
config/templates/grids/userRoles-grid/actions/grid/new-item.vue
config/templates/grids/userRoles-grid/actions/row-select/assignRole.vue
config/templates/grids/userRoles-grid/actions/row-select/delete-item.vue
config/templates/grids/userRoles-grid/actions/row-select/index.vue
config/templates/grids/userRoles-grid/column-rolemappings.vue

- Added the add user,edit roles,and delete user from the user section
- added the access key and secret key generation functionality

Feat org user role:Added the user and access key creation in org section 

---

pages/apps/_app/organization/_id/editOrgInfoForm.vue
pages/apps/_app/organization/_id/editOrgSetting.vue
pages/apps/_app/organization/_id/editSocialMedia.vue
pages/apps/_app/organization/_id/editWorkTiming.vue
pages/apps/_app/organization/_id/index.vue

added the edit org info form,edit org settings form,edit org media setting form,edit work timings form in organization section

feat_org_edit_info_form:added the edit form in organization section

---

assets/styles/main.css
config/templates/grids/discount-grid/column-isactive.vue
config/templates/grids/discount-grid/column-ispercent.vue
config/templates/grids/eventDiscountCode-grid/column-isactive.vue
config/templates/grids/eventRegistrationForm-grid/column-isattendeefield.vue
config/templates/grids/eventRegistrationForm-grid/column-isrequired.vue
config/templates/grids/eventRegistrationForm-grid/column-isshowfield.vue
config/templates/grids/livedraft-grid/body.vue
config/templates/grids/organizationBussinessUnit-grid/column-default.vue
layouts/admin.vue
layouts/default.vue
layouts/event.vue
layouts/flatlayout.vue
nuxt.config.js
pages/apps/_app/event/_id/index.vue
pages/apps/_app/organization/_id/index.vue

#Checkbox changes
#grid alignment
#topbar shadow on hover

Bug ui fixes v5

---

components/common/form/richtext.vue
config/apps/admin/content/badge.js
config/apps/admin/content/marketingtemplates.js
config/apps/event/content/contacts.js
config/apps/event/content/event.js
config/apps/event/content/registrations.js
config/common/templates/grid/actions/grid/new-item.vue
config/templates/grids/eventInvites-grid/actions/grid/index.vue
config/templates/grids/eventInvites-grid/actions/grid/refresh.vue
config/templates/grids/registrationAbondoned-grid/column-0.vue
config/templates/grids/registrationAbondoned-grid/column-status.vue
pages/apps/_app/registration/_id/index.vue

Added refresh action event Invite grid,
Added dropdown for RTE in New Template and Badge,
Issues

Feat event invite action

---

assets/styles/main.css
config/apps/admin/content/seatmaps.js
config/apps/event/content/event.js
config/templates/grids/eventIntegration-grid/column-integrate.vue
config/templates/grids/eventIntegration-grid/column-serviceid.vue
config/templates/grids/eventRecurringSession-grid/column-isactive.vue
config/templates/grids/eventRecurringSession-grid/column-seatreservation.vue
config/templates/grids/livedraft-grid/body.vue
nuxt.config.js
pages/apps/_app/organization/_id/index.vue
pages/apps/_app/registration/_id/index.vue
pages/apps/_app/registration/activity/_id/index.vue
pages/index.vue

#Bug fixes
#login with google method added on login page

Bug ui fixes v6

---

config/templates/grids/eventTickets-grid/actions/grid/new-item.vue
config/templates/grids/eventTickets-grid/actions/row-select/edit-item.vue
pages/apps/_app/event/_id/editSiteSetting.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue

Fixed the  conditinal rendering of next,prev,save button in the event site settings
After publishing event success message display
Fixed stepper in recurring event
Fixed the ticket validation issue and rendering based on type of event

bug_1:Tabs button redering issue  in event settings

---

components/common/form/richtext.vue
config/apps/admin/content/organization.js
config/apps/event/content/contacts.js
config/apps/event/content/discountcodes.js
config/apps/event/content/event.js
config/apps/event/content/registrations.js
config/templates/grids/eventInvites-grid/actions/grid/sendEventInvite.vue
config/templates/grids/eventRegistrations-grid/actions/row-select/resendRegistrationEmail.vue
config/templates/grids/registrationAttendees-grid/actions/row-select/index.vue
config/templates/grids/registrationAttendees-grid/actions/row-select/print-badges.vue
config/templates/grids/registrationAttendees-grid/column-checkin.vue
pages/apps/_app/event/_id/editEventForm.vue

Fix: RTE issue
Invitation grid issues
Resend Email fix
Default form fixes

Bug event fixes v1

---

components/newRecurringEvent.vue
components/newSingleEvent.vue
config/apps/event/gql/location.gql
config/templates/grids/discountMember-grid/actions/grid/new-item.vue
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
config/templates/grids/livedraft-grid/body.vue
nuxt.config.js
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/_id/makeCopy.vue

Copy event functionality from event tile and resolved some issues of recurring event, make copy, recurring session, single event.

Feat tile event copy

---

components/common/form/search.vue
config/apps/event/content/registrations.js
config/apps/event/gql/registrationList.gql
utility/form.js
utility/object.js

add search field by type='search'

feat: add search control with graphql

---

pages/apps/_app/contacts/_id/index.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/organization/_id/index.vue

Added upload functionality in contact section
Added upload functionality in org section

Bug 3 upload btn func:Fixed the upload btn in the event detail view

---

components/common/form/date.vue
config/templates/grids/eventRegistrationQuestion-grid/actions/grid/new-item.vue
config/templates/grids/eventRegistrationQuestion-grid/actions/row-select/edit-item.vue
config/templates/grids/eventTickets-grid/actions/grid/new-item.vue
config/templates/grids/livedraft-grid/body.vue
pages/apps/_app/event/_id/editEventForm.vue
pages/apps/_app/event/_id/editEventSetting.vue
pages/apps/_app/event/_id/editSeoForm.vue
pages/apps/_app/event/_id/editSiteSetting.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue
pages/apps/_app/organization/_id/editOrgInfoForm.vue
pages/apps/_app/organization/_id/editOrgSetting.vue
pages/apps/_app/organization/_id/editSocialMedia.vue
pages/apps/_app/organization/_id/editWorkTiming.vue
pages/apps/_app/organization/_id/index.vue

Resetting the form in the event edit form
Resetting the form in the org edit form
Resetting the form in the ticket add,edit form
Resetting the form in the registration question add,edit form
Fixed the publishing event snackbar UI
Resetting the form on the edit section from tiles

Bug 4 reset form:Added the reset form functionality 

---

config/apps/event/content/event.js
config/templates/grids/eventRegistrationForm-grid/actions/row-select/edit-item.vue
pages/apps/_app/event/_id/index.vue

Added the edit registration form functionality in event detail view form
Fixed the issue of on closing the upload window form site crashed

Feat edit registration form settings:added the edit registration form

---

config/templates/grids/eventTickets-grid/actions/row-select/delete-item.vue
pages/apps/_app/event/_id/editEventForm.vue
pages/apps/_app/event/_id/editEventSetting.vue
pages/apps/_app/event/_id/index.vue

Fixed issue of duplicating the event link showing "Already taken message " in event settings
Fixed issue of badge displayed in online event form
Fixed issue of snackbar not showing when tickets deleted

Bug_5:Fixed issues 

---

components/newRecurringEvent.vue
config/apps/event/gql/eventRecurringSession.gql
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
config/templates/grids/eventRecurringSession-grid/actions/row-select/edit-item.vue
config/templates/grids/eventRecurringSession-grid/actions/row-select/index.vue

Edit Recurring session functionality, New recurring session reset form issue,  recurring event issue

Feat edit recurring session

---

layouts/event.vue
utility/oauth.js

1. all the integration links are redirecting event.test.bitpod.io on organization and event level 
2. .Session Expired issue 
https://www.loom.com/share/9a99d8b52c0f4b1cadc6e9fe6f00d51a

fix: resolved session expired and oauth issue

---

config/apps/event/gql/event.gql
config/apps/event/gql/eventlist.gql
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/_id/selectExistingSeatMap.vue
pages/apps/_app/event/recurring/_id/index.vue
pages/apps/_app/seatmap/_id/index.vue

Added seat map functionality on event ticket grid

Feat event seatmap

---

config/apps/admin/content/organization.js
config/apps/event/content/contacts.js
config/common/templates/grid/actions/grid/new-item.vue
config/common/templates/grid/actions/row-select/edit-item.vue
config/templates/grids/organizationBussinessUnit-grid/column-action.vue
pages/apps/_app/event/_id/selectExistingSeatMap.vue
pages/apps/_app/seatmap/_id/index.vue

Added seatmap feat on admin
Default New/Edit contact form changes to avoid duplicate email to store

Feat admin seatmap

---

config/apps/event/content/event.js
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue

Resolved issues #373,#379 for event registration site not getting open

Resolved issues

---

nuxt.config.js
pages/apps/_app/attendee/_id/index.vue

#icons added 
#skeleton added for public page

Feat public page

---

components/common/copy/index.vue
components/common/form/richtext.vue
components/newRecurringEvent.vue
components/newSingleEvent.vue
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
config/templates/grids/eventRegistrations-grid/column-golive.vue
config/templates/grids/eventSession-grid/actions/form.vue
config/templates/grids/eventSession-grid/column-duration.vue
config/templates/grids/eventSession-grid/column-golive.vue
pages/apps/_app/event/_id/index.vue
utility/rules.js

timezone issue fix, other ui fixes,copy buttons and tooltip added.

demo changes

---

components/common/form/richtext.vue
config/templates/grids/eventTickets-grid/actions/grid/new-item.vue
config/templates/grids/eventTickets-grid/actions/row-select/delete-item.vue
config/templates/grids/eventTickets-grid/actions/row-select/edit-item.vue
pages/apps/_app/organization/_id/editOrgInfoForm.vue

Fixed the issue of ticket date validation in recurring event
Fixed the time picker not updating the v-model data on click outside the picker
Fixed the issue of organization info address not getting saved

Bug 7 ticket date issue

---

components/common/app-drawer/index.vue
layouts/admin.vue
layouts/event.vue
layouts/seatmap.vue
middleware/authorization.js
nuxt.config.js
pages/apps/_app/list/_contentName/_viewName/index.vue
pages/login/index.vue
pages/unauthorized.vue
utility/userApps.js

add middleware to redirect user to org-specific domain
add "p" query param for login provider

Feat: redirect user to org-specific domain

---

config/apps/event/content/event.js
config/apps/event/gql/eventSession.gql
config/templates/grids/eventSession-grid/actions/form.vue
config/templates/grids/eventSession-grid/column-golive.vue

- Positioning of buttons in session grid
- undefined room fix
- type venue address fix

resolved demo issue

---

assets/styles/main.css
components/common/grid/index.vue
components/newRecurringEvent.vue
components/newSingleEvent.vue
config/apps/admin/content/marketingtemplates.js
config/apps/seatmap/content/seatmaps.js
config/templates/grids/discount-grid/column-isactive.vue
layouts/event.vue
nuxt.config.js
pages/apps/_app/attendee/_id/index.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue
pages/apps/_app/organization/_id/index.vue
pages/apps/_app/seatmap/seatmap/index.vue

#Lounge public page issue
#resolved UI issue

Feat ui fixes v9

---

config/templates/grids/eventSession-grid/actions/form.vue
nuxt.config.js
pages/apps/_app/eventboard/index.vue

- Event board issues fixed
- few demo related changes also added
- Session form ui feedback added

Issue list

---

components/newRecurringEvent.vue
components/newSingleEvent.vue
config/apps/event/gql/organizationInfo.gql
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
nuxt.config.js
pages/apps/_app/registration/_id/cancelRegistration.vue
pages/apps/_app/registration/_id/editRegistration.vue
pages/apps/_app/registration/_id/refundRegistration.vue
strings.js

Resolved issues of single event, new/edit session, registration actions and reset form issues

Issue fixes v1

---

config/apps/event/gql/registration.gql
config/templates/grids/eventTickets-grid/actions/grid/new-item.vue
pages/apps/_app/event/_id/editEventForm.vue
pages/apps/_app/registration/_id/index.vue
pages/apps/_app/seatmap/_id/index.vue
plugins/bitpod/getApiUrl.js

Fixed:-
+When we are editing the timezone from the edit event form eventdate was getting changed based on timezone which should not be 
+Edit forms are not getting clear on tile view (if i open edit form and edit title and close it and again open it then shows edited title )
+Fixed the ticket end date validation error replaced it with event end date
+On registration detail view not getting not getting all the event infornmation and payment details
+Fixed the issue of warning message of gettingOrgUrl while deployment

Bug 8 timezone issue

---

components/newRecurringEvent.vue
components/newSingleEvent.vue
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
config/templates/grids/livedraft-grid/body.vue
pages/apps/_app/event/_id/makeCopy.vue

Resolved below issues :-  
#237,#318,#371, #251
delete ticket issue on create event form 
ticket end date issue when adding new ticket 
Added hand on hover of make a copy link on 3 dots

Issue fixes v2

---

config/templates/grids/eventAttendees-grid/actions/row-select/print-badges.vue
config/templates/grids/eventAttendees-grid/column-checkin.vue
config/templates/grids/registrationAttendees-grid/actions/row-select/print-badges.vue
config/templates/grids/registrationAttendees-grid/column-checkin.vue
layouts/admin.vue
pages/apps/_app/event/_id/index.vue

+FIxed the issue of double window opening while clicking the print badge option
+Added the custom create user form globally

bug_printBadge:fixed double screen open while printing the badges

---

config/templates/grids/eventInvites-grid/actions/grid/sendEventInvite.vue
config/templates/grids/eventSession-grid/actions/form.vue

fixed template name issue

---

components/common/form/richtext.vue
components/common/grid/index.vue
config/apps/admin/content/marketingtemplates.js
config/common/templates/grid/actions/grid/new-item.vue
config/common/templates/grid/actions/row-select/edit-item.vue
config/templates/grids/eventRecurringSession-grid/column-seatreservation.vue
config/templates/grids/eventRegistrations-grid/actions/row-select/resendRegistrationEmail.vue
config/templates/grids/registration-grid/actions/row-select/resendRegistrationEmail.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/seatmap/_id/index.vue

Bug event fixes v6

---

config/apps/admin/gql/businessUnit.gql
config/apps/event/gql/eventlist.gql
config/apps/event/gql/liveDraftevents.gql

Fix for UI breaking issue when going back to live & draft from detail vue.

My template save feat

---

assets/styles/main.css
components/common/copy/index.vue
components/common/form/date.vue
config/templates/grids/eventRegistrationQuestion-grid/actions/grid/new-item.vue
config/templates/grids/eventRegistrationQuestion-grid/actions/row-select/delete-item.vue
config/templates/grids/eventRegistrationQuestion-grid/actions/row-select/edit-item.vue
config/templates/grids/eventRegistrationQuestion-grid/column-options.vue
config/templates/grids/eventSession-grid/actions/form.vue
config/templates/grids/livedraft-grid/body.vue
config/templates/grids/registration-grid/column-status.vue
layouts/logoutlayout.vue
nuxt.config.js
pages/apps/_app/event/_id/makeCopy.vue
pages/apps/_app/event/invite/_id/index.vue
pages/login/index.vue

Feat oct issue v2

---

assets/styles/main.css
components/common/form/richtext.vue
components/common/notes/index.vue
pages/apps/_app/eventboard/index.vue

resolved 2 criticles
- not able to type in rte Popups
- full screen exit issue on back

Rte critcal issues

---

assets/styles/main.css

missed one ui issue

---

assets/styles/main.css
components/common/form/date.vue
components/newRecurringEvent.vue
components/newSingleEvent.vue
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
config/templates/grids/eventRecurringSession-grid/column-ticketname.vue

Resolved issues related with location online event validation msg, scrolling issue, overlap msg issue
#349,#348,#411,#7,#353,#405,#331

Issue fixes v3

---

config/templates/grids/eventAttendees-grid/actions/row-select/print-badges.vue
config/templates/grids/eventAttendees-grid/column-checkin.vue
config/templates/grids/eventTickets-grid/actions/grid/new-item.vue
config/templates/grids/eventTickets-grid/actions/row-select/edit-item.vue
config/templates/grids/livedraft-grid/body.vue
config/templates/grids/registrationAttendees-grid/actions/row-select/print-badges.vue
config/templates/grids/registrationAttendees-grid/column-checkin.vue
pages/apps/_app/event/_id/editEventSetting.vue
pages/apps/_app/event/_id/index.vue

Fixed:-
#374: new ticket form not getting clear now
#372: on attendee and reg page shows the same image 
#368: UI moves in the edit registration form due to the error message
#416:ticket count should be mandatory and add some default value
#398 : View all should redirect from event tile view

Bug 11 badge image

---

assets/styles/main.css
components/common/notes/index.vue
config/common/templates/grid/actions/row-select/delete-item.vue
config/templates/grids/accessKey-grid/column-3.vue
config/templates/grids/badge-grid/body.vue
config/templates/grids/eventAttendees-grid/column-action.vue
config/templates/grids/eventTickets-grid/actions/row-select/delete-item.vue
config/templates/grids/invitetemplate-grid/body.vue
config/templates/grids/livedraft-grid/body.vue
config/templates/grids/mytemplate-grid/body.vue
config/templates/grids/registrationform-grid/column-isattendeefield.vue
config/templates/grids/registrationform-grid/column-isrequired.vue
config/templates/grids/registrationform-grid/column-isshowfield.vue
nuxt.config.js
package.json
pages/apps/_app/event/_id/index.vue
pages/apps/_app/organization/lookups/index.vue
plugins/v-confirm/Confirm.vue
plugins/v-confirm/index.js
plugins/v-confirm/vuetify-confirm.js
yarn.lock

#Alert UI Issue
#Resolved some Issue
#i18n UI issue for headings in pages

Feat issue oct v3

---

assets/styles/main.css
components/common/grid/index.vue
layouts/admin.vue
layouts/event.vue
nuxt.config.js
pages/apps/_app/contacts/_id/index.vue
pages/apps/_app/discountcodes/_id/index.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue
pages/apps/_app/organization/_id/index.vue
pages/apps/_app/registration/_id/index.vue

#internationalization UI Fixes
#tooltip added
#form UI fixes
#layout fixes for hn lang

Internalization ui

---

assets/styles/main.css
config/apps/admin/content/lookup.js
config/apps/admin/content/marketingtemplates.js
config/apps/admin/content/organization.js
config/apps/admin/content/registrationformdetails.js
config/apps/event/content/contacts.js
config/apps/event/content/discountcodes.js
config/apps/event/content/event.js
config/apps/event/content/eventRegistrationType.js
config/apps/event/content/eventcustomers.js
config/apps/event/content/registrations.js
config/apps/seatmap/content/seatmaps.js
config/common/templates/grid/actions/grid/new-item.vue
config/common/templates/grid/actions/row-select/delete-item.vue
config/common/templates/grid/actions/row-select/edit-item.vue
config/templates/grids/allEvents-grid/column-0.vue
layouts/admin.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
utility/form.js

Bug i18n v1

---

config/apps/event/content/event.js
config/templates/grids/eventInvites-grid/actions/grid/sendEventInvite.vue
config/templates/grids/eventTask-grid/edit-template.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/event/invite/_id/index.vue

- draft edit delete feat.
- hardcoded string to i18
- new confirmation dialog
- small ui fixes

draft feat.

---

pages/apps/_app/contacts/_id/index.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue

Fixed:-
+423: In contact detail view dob format should be proper
+415: upload image misbehaves when i upload multiple images same time In first row shows three images and in second row shows four images all row should have same number of images

Bug 13 upload bulk other image

---

components/common/form/datetime-picker.vue
config/apps/admin/content/badge.js
config/apps/admin/content/marketingtemplates.js
config/apps/admin/content/organization.js
config/apps/admin/content/registrationformdetails.js
config/apps/admin/content/userroles.js
config/apps/event/content/contacts.js
config/apps/event/content/event.js
config/apps/event/content/eventIntegrations.js
config/apps/event/content/registrations.js
config/common/templates/grid/actions/grid/new-item.vue
config/common/templates/grid/actions/row-select/delete-item.vue
config/common/templates/grid/actions/row-select/edit-item.vue
config/templates/grids/contact-grid/column-0.vue
config/templates/grids/discount-grid/column-0.vue
config/templates/grids/eventRecurringSession-grid/column-scheduledtype.vue
config/templates/grids/eventTask-grid/actions/grid/new-item.vue
config/templates/grids/livedraft-grid/body.vue
config/templates/grids/organizationTask-grid/actions/grid/new-item.vue
config/templates/grids/organizationTask-grid/actions/row-select/edit-item.vue
config/templates/grids/registrationEmails-grid/column-0.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
utility/form.js

Bug event fixes v7

---

assets/styles/main.css
layouts/event.vue
nuxt.config.js

1. skeleton loading of grid
2. initial rendering nav closed issue
3. embeded field apollo data cache issue

Bug nav issue

---

assets/styles/main.css
config/templates/grids/allEvents-grid/column-0.vue
config/templates/grids/allEvents-grid/column-tags.vue
config/templates/grids/livedraft-grid/body.vue
config/templates/grids/pastEvents-grid/column-0.vue
layouts/admin.vue
layouts/event.vue
layouts/logoutlayout.vue
locales/fr.json
nuxt.config.js
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue

#Resolved UI Issues
#Mobile Issue

Nov issue v1

---

components/newRecurringEvent.vue
components/newSingleEvent.vue
config/templates/grids/eventTask-grid/actions/grid/new-item.vue
config/templates/grids/eventTask-grid/edit-template.vue

Resolved issues - #566,#577,#592,#593

Issue fixes v6

---

components/common/form/richtext.vue
components/common/recurringCalendar/index.vue
components/common/saveButton/index.vue
config/common/templates/grid/actions/grid/new-item.vue
config/common/templates/grid/actions/row-select/edit-item.vue
config/templates/grids/eventSession-grid/actions/form.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/event/invite/_id/index.vue
pages/apps/_app/organization/_id/editWorkTiming.vue

resolved 
- 4 criticals
- 1 bloker
- ui and validations issue

New issues

---

assets/styles/main.css
config/templates/grids/integrationapp-grid/body.vue
config/templates/grids/seatmap-grid/body.vue
nuxt.config.js
pages/apps/_app/attendee/_id/index.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue
pages/apps/_app/registration/_id/index.vue
pages/apps/_app/seatmap/seatmap/index.vue

#resolved Issues
#Mobile issues

Nov issue v4

---

pages/apps/_app/contacts/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue
pages/apps/_app/organization/_id/index.vue

FIxed:
+516: At the administration check the upload button on top section not able to see the logo after upload (upload not working ) Same issue on contact detail view
+610: copy link option is not working in copy link page from event detail view

bug_17:Fixed recurring event copy link option

---

components/newRecurringEvent.vue
components/newSingleEvent.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue

Issue fixes v9

---

components/common/app-drawer/index.vue
config/apps/list.js
layouts/admin.vue
layouts/integration.vue
middleware/authorization.js
nuxt.config.js
store/index.js

1. org info not showing on org details page for orgs other than prime 
2. using old/expired jwt token for graphql requests

Bug: org info not showing 

---

components/newRecurringEvent.vue
components/newSingleEvent.vue

Resolved issues -
#692,#584
online meeting location validation issue

Issue fixes v10

---

config/templates/grids/eventRegistrationQuestion-grid/actions/grid/new-item.vue
config/templates/grids/eventRegistrationQuestion-grid/actions/row-select/edit-item.vue
config/templates/grids/eventTickets-grid/actions/grid/new-item.vue
config/templates/grids/eventTickets-grid/actions/row-select/edit-item.vue
pages/apps/_app/organization/_id/index.vue

Fixed:
+685:on save button loader should add for tickets and registration question grid
+670:At administration section, added upload button and gallery section

Bug_20:save button issue

---

pages/apps/_app/registration/_id/index.vue

Bug event fixes v13

---

components/common/grid/index.vue
components/common/notes/index.vue
config/templates/grids/eventInvites-grid/actions/grid/sendEventInvite.vue
config/templates/grids/eventSession-grid/column-ticketname.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/eventboard/index.vue
pages/apps/_app/registration/_id/index.vue
utility/rules.js

resolved 4 major and few criticals

Reassigned

---

components/common/grid/FieldsFilter.vue
config/apps/event/content/event.js
config/templates/grids/allEvents-grid/actions/row-select/edit-item.vue
config/templates/grids/integrationapp-grid/body.vue
pages/apps/_app/event/_id/index.vue

Bug event fixes v15

---

locales/en-US.json
locales/fr.json
nuxt.config.js
pages/apps/_app/attendee/_id/index.vue

#resolved loung pages issue
#resolved 2nd org images issue

Nov issue v9

---

components/common/grid/index.vue
config/apps/admin/content/organization.js
config/apps/event/content/event.js
config/templates/grids/eventIntegration-grid/stripe.vue
config/templates/grids/integrationapp-grid/body.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue
pages/apps/_app/organization/_id/index.vue

Resolved issue #702 and stripe Payment Setup form issue.

Bug event fixes v16

---

assets/styles/main.css
components/common/grid/FieldsFilter.vue
nuxt.config.js
pages/apps/_app/attendee/_id/index.vue

Nov issue v11

---

components/common/saveButton/index.vue
components/newRecurringEvent.vue
components/newSingleEvent.vue
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
config/templates/grids/eventTask-grid/actions/grid/new-item.vue
config/templates/grids/eventTask-grid/edit-template.vue
pages/apps/_app/event/_id/makeCopy.vue
pages/apps/_app/organization/_id/editBadgeTemplate.vue
pages/apps/_app/organization/_id/editInviteMetadata.vue
pages/apps/_app/organization/_id/editInviteTemplate.vue
pages/apps/_app/registration/_id/cancelRegistration.vue
pages/apps/_app/registration/_id/editRegistration.vue
pages/apps/_app/registration/_id/refundRegistration.vue

Added loader in some forms(#705)
reset loader functionality
resolved issues - #727,#728

added loader in some form, reset loader functionality and some issues

---

nuxt.config.js
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue

Nov issue v12

---

components/common/grid/index.vue
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue

Resolved issue
#603 - when i edit the session without selecting a record then not getting data in edit form

Issue fixes v13

---

config/common/templates/grid/actions/row-select/edit-item.vue
pages/login/index.vue

Issue #404 when i select the record , edit this record and close the form and didnt click anywhere else and again edit the record then form not get clear 
issue related to login page shows on org based domain login

fix: add edit action data issue

---

config/templates/grids/eventTickets-grid/actions/row-select/edit-item.vue

Resolved fix for #712

---

assets/styles/main.css
locales/en-US.json
nuxt.config.js

Nov issue v13

---

config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
pages/apps/_app/registration/_id/cancelRegistration.vue
pages/apps/_app/registration/_id/editRegistration.vue
pages/apps/_app/registration/_id/index.vue
pages/apps/_app/registration/_id/refundRegistration.vue

1) refresh registration data issue after edit,cancel, refund actions
2)  toast message issue of edit recurring session form

Issue fixes v14

---

components/newRecurringEvent.vue
components/newSingleEvent.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue

Bug event fixes v19

---

config/templates/grids/eventSession-grid/actions/form.vue

- bitpod virtual link missing fix

fix for 2 criticals

---

assets/styles/main.css
components/common/grid/index.vue
nuxt.config.js
pages/apps/_app/event/_id/index.vue

Nov issue v14

---

assets/styles/main.css
nuxt.config.js
pages/apps/_app/event/_id/index.vue
pages/apps/_app/organization/_id/index.vue

#Mobile issue fix
#upload buttton

Nov issue v15

---

config/templates/grids/livedraft-grid/body.vue
nuxt.config.js
pages/apps/_app/attendee/_id/index.vue
pages/apps/_app/event/_id/editEventSetting.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue

move `eventUrl` config var to publicRuntimeConfig
- fixes `eventUrl` not using ENV value.

Fix `eventUrl` not using ENV value - 765

---

config/templates/grids/eventRegistrations-grid/column-golive.vue
config/templates/grids/eventSession-grid/column-golive.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/eventboard/index.vue
pages/apps/_app/live/_id/index.vue

diffent symbols depending on org's currenct fix

currency symbol fix

---

config/templates/grids/badge-grid/body.vue
config/templates/grids/eventTask-grid/actions/grid/new-item.vue
config/templates/grids/eventTask-grid/column-templateaction.vue
config/templates/grids/eventTask-grid/edit-surveytemplate.vue
config/templates/grids/eventTask-grid/edit-template.vue
config/templates/grids/invitetemplate-grid/body.vue
config/templates/grids/mytemplate-grid/body.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/organization/_id/editBadgeTemplate.vue
pages/apps/_app/organization/_id/editInviteMetadata.vue
pages/apps/_app/organization/_id/editInviteTemplate.vue

Added toast msg in Invitetemplate - editInviteMetadata, editInviteTemplate, 
mytemplate - editInviteMetadata, editInviteTemplate, 
badgetemplate
added loader in edit surveytemplate
made some localization changes

added some toast msg , loader and some localization changes

---

components/common/copy/index.vue
components/common/grid/index.vue
components/common/recurringCalendar/index.vue
config/templates/grids/eventSession-grid/actions/form.vue
locales/he.json

- Ui fixes
- added checks for mobile view (IPhone related issue)

fixed few ui issues,

---

assets/styles/main.css
components/common/grid/index.vue
components/common/recurringCalendar/index.vue
config/templates/grids/integrationapp-grid/body.vue
layouts/integration.vue
pages/apps/_app/live/_id/index.vue

- custom API response param changes
- fix for 1 i-phone related issue
- added missing headers and other UI fixes

resolved ui issues for iphone

---

layouts/event.vue
pages/apps/_app/contacts/_id/index.vue

Fixed:-
+516:At the administration the upload button on top section not able to see the logo after upload.And fixed the UI changes of contact avataar on uploading an image
+429:Navigation bar should be selected when go to detail view in registration detail view and contact detail view

Bug 20 nav bar issue

---

assets/styles/main.css
config/templates/grids/integrationapp-grid/body.vue

785 issue resolved

---

components/common/grid/index.vue
config/common/templates/grid/actions/grid/new-item.vue
config/common/templates/grid/actions/row-select/edit-item.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/eventboard/index.vue
utility/index.js

Resolved 783,774,775 and added console for #691

Major bug event fixes v1

---

components/newRecurringEvent.vue
components/newSingleEvent.vue
pages/apps/_app/event/_id/makeCopy.vue

Issue fixes v20

---

components/common/grid/FieldsFilter.vue

- Fixed `Add a Filter` button not appearing
- Possible fix of content overlap

possible iphone overlap fix 616

---

assets/styles/main.css
config/apps/event/gql/event.gql
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/attendee/_id/index.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue

Dec issue v2

---

api/index.js
nuxt.config.js
package.json
yarn.lock

FIxed:-
+issue of not able to choose account in google and bitpod
+issue of redirecting to login screen after logout

Bug 21 logout issue

---

assets/styles/main.css
components/newRecurringEvent.vue
components/newSingleEvent.vue
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
pages/apps/_app/event/_id/editEventForm.vue
pages/apps/_app/event/_id/makeCopy.vue

#440 - not getting names for address 
resolved for a) new single event b) copy event from tile c) copy event from event detail page d) new recurring session e) edit recurrign session
#657 - location field validation is getting cut for Hindi language
#804 - On create recurring event page tickets and timezone are not mandatory still showing star mark on session tab

Issue fixes v18

---

config/templates/grids/eventInvites-grid/actions/grid/sendEventInvite.vue
config/templates/grids/eventTask-grid/edit-template.vue
config/templates/grids/invitetemplate-grid/body.vue
config/templates/grids/mytemplate-grid/body.vue
pages/apps/_app/event/_id/editSiteSetting.vue

Left over majors

---

components/common/grid/FieldFilter.vue

possible overflow fix for filter fields

resize input sizes to prevent overflow - 790

---

components/newRecurringEvent.vue
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue

Resolved issues - 
#806 - On edit session form location field is looking very small priviously it was full screen 
#812 - while creating recurring event when i select session as custom and close it then pin code not get clear

Issue fixes v21

---

components/common/copy/index.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/event/_id/editBadgeForm.vue
pages/apps/_app/event/_id/editEventForm.vue
pages/apps/_app/event/_id/editEventSetting.vue
pages/apps/_app/event/_id/editSeoForm.vue
pages/apps/_app/event/_id/editSiteSetting.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/_id/newBadgeForm.vue

Fixed:
+808:Not able to save the changes in event edit,seo edit form  in copy of recurring event getting 502 error on console when click on save
+816:if we edit event settings change event link and save wrong message is getting "badge are deleted successfully"
+copy to clipboard in iphone

Bug 23:Badge toaster issue and copy to clipboard issue in iphone

---

components/common/grid/index.vue
pages/apps/_app/discountcodes/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue
pages/apps/_app/registration/_id/index.vue

- switch to inline-block for possible ios fix

patch fix for sticky headers in 724

---

components/common/copy/index.vue
config/templates/grids/eventAttendees-grid/actions/grid/index.vue
config/templates/grids/eventTickets-grid/actions/grid/seatmapTickets.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/contacts/_id/index.vue
pages/apps/_app/event/_id/editEventForm.vue
pages/apps/_app/event/_id/editEventSetting.vue
pages/apps/_app/event/recurring/_id/index.vue

Fixed:-
+802:From event settings form make an event link filed same as create event form
+added toaster in the recurring event
+added checks for the copy to clipboard functionality in iphone

Bug_22:fixed issue of uniqueLink UI

---

components/common/grid/index.vue

I would like to add some console logs to get more information when this error occurs on test env.
Issue Number 388:
> When i go to template tab then first time loads the data in grid not in tile  (same issue with event tab on admin and on seatmap )

add console debugs for random issue 388

---

components/common/form/date.vue
components/common/grid/index.vue
config/apps/event/content/eventIntegrations.js
config/templates/grids/eventTickets-grid/actions/grid/new-item.vue
config/templates/grids/eventTickets-grid/actions/row-select/edit-item.vue
config/templates/grids/eventTickets-grid/column-amount.vue
config/templates/grids/seatmap-grid/body.vue
pages/apps/_app/event/_id/editEventSetting.vue
pages/apps/_app/event/_id/index.vue

Resolved issues #30,#188,#304,#312,#334,#344,#574,#691,#292,#302,#346,#380,#501,#503,#360,#686,#739,#695,#310

Major bug event fixes v3

---

components/newSingleEvent.vue
config/templates/grids/allEvents-grid/actions/row-select/edit-item.vue
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
pages/apps/_app/event/_id/editEventForm.vue
pages/apps/_app/event/_id/makeCopy.vue

Resolved issue - #810 - "Add an address title for address field on
1) edit event from from tile
2) edit event form from all events
3) edit event form from event detail view
4) make copy 
"

Issue fixes v23

---

package.json

update version number to 1.1.2

---

config/apps/list.js
layouts/default.vue
pages/apps/_app/event/_id/editEventForm.vue
pages/apps/_app/seatmap/seatmap/index.vue

Dec issues v6

---

components/common/grid/index.vue
pages/apps/_app/list/_contentName/_viewName/index.vue

Convert actions div to a block as a fix for safari.

fix iOS list sticky issue

---

config/templates/grids/userRoles-grid/actions/row-select/assignRole.vue
pages/apps/_app/event/_id/editEventForm.vue

Fixed:
+837:assign role form not getting clear from administration.
+831:When i create an event without description and then edit event info and add description then not loading map on reg. page and if user register for this event then not loads the map from mail also.

Bug 25 registration name not showing in registration detail view.

---

components/common/grid/FieldFilter.vue
config/templates/grids/eventInvites-grid/actions/grid/refresh.vue
config/templates/grids/eventRegistrations-grid/actions/row-select/resendRegistrationEmail.vue
config/templates/grids/registration-grid/actions/row-select/resendRegistrationEmail.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/event/_id/index.vue
pages/apps/_app/seatmap/_id/index.vue
pages/apps/_app/seatmap/seatmap/index.vue

Resolved issues #823,#824,#828,#441

Major bug event fixes v4

---

components/common/app-drawer/index.vue
config/apps/list.js
layouts/admin.vue
layouts/default.vue
layouts/event.vue
layouts/integration.vue
layouts/seatmap.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json

#821 issue fix 
#survey icon changed
#seatmap lable changed

Dec issues v7

---

components/common/notes/index.vue
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue

resolved 2 issues

---

components/common/grid/index.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/event/_id/index.vue
pages/apps/_app/seatmap/seatmap/index.vue

Resolved issues #621,#823,#777

Major bug event fixes v5

---

components/common/grid/index.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/attendee/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue

#lounge page issue resolved
#skeleton issue solved

Dec issue v8

---

components/common/grid/index.vue
components/common/notes/index.vue
config/templates/grids/eventInvites-grid/actions/grid/refresh.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json

Major bug event fixes v6

---

config/templates/grids/eventTask-grid/edit-surveytemplate.vue

Resolved issue

---

components/common/oldsite/index.vue
config/apps/list.js
layouts/admin.vue
layouts/event.vue
layouts/integration.vue
layouts/seatmap.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json

#survey link changed
#added go to old site link

Dec issue v9

---

components/common/organization-list/organization-list.vue
nuxt.config.js

Moved the hard coded env  variables to public runtime config

Bug 27 org prod issue

---

components/common/grid/FieldFilter.vue
components/common/grid/FieldsFilter.vue
components/common/grid/index.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/event/_id/index.vue
pages/apps/_app/seatmap/_id/index.vue

Resolved issues #232, #210 and snackbar issues

Major bug event fixes v9

---

components/common/grid/index.vue
components/common/help/index.vue
config/apps/list.js
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue

Dec issue 16

---

config/templates/grids/eventTask-grid/actions/grid/new-item.vue
config/templates/grids/organizationTask-grid/actions/grid/new-item.vue

Fixed:-
+886:due date on scheduled task form is marked as mandatory but actually not at administration
+887:not getting due date and timezone on edit survey scheduled form from admin and event detail view

Bug 27:date and day not showing in task 

---

config/templates/grids/eventRegistrationQuestion-grid/actions/row-select/delete-item.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/_id/makeCopy.vue

Fixed:
+834:from copy event form make an event link same like as create event form
+869:check the delete reg question and  delete image confirnmation box heading

fixed issue of toster color and uniqlink error message

---

components/newRecurringEvent.vue
components/newSingleEvent.vue
config/templates/grids/allEvents-grid/actions/row-select/edit-item.vue
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
config/templates/grids/eventRegistrations-grid/column-golive.vue
config/templates/grids/eventSession-grid/actions/form.vue
config/templates/grids/eventSession-grid/column-golive.vue
nuxt.config.js
pages/apps/_app/event/_id/editEventForm.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/live/_id/index.vue

- Makes `integrationLinks` accessible via nuxt public runtime configs so that it respects values of env vars.

migrate integrationLinks to nuxt runtime config

---

config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
config/templates/grids/eventTask-grid/actions/grid/new-item.vue
config/templates/grids/organizationTask-grid/actions/grid/new-item.vue
pages/apps/_app/event/_id/makeCopy.vue
pages/apps/_app/event/recurring/_id/index.vue

Fixed:-
#891:Task form is not getting clear if i add the due date then it get assign to all type of categories 
#892:when i create new survey task with scheduled type then sometimes shows due date as prefilled 
#853:when i select the location type as custom then save button should be disabled like other type untill user add address
#834:from copy event form make an event link same like as create event form

Bug 29:Fixed the link issue

---

package.json

- create patch release `1.1.4`.

update patch version

---

config/apps/admin/content/organization.js
config/apps/event/gql/registration.gql
config/templates/grids/eventRegistrationQuestion-grid/actions/row-select/delete-item.vue
config/templates/grids/eventTask-grid/actions/grid/new-item.vue
config/templates/grids/organizationTask-grid/actions/grid/new-item.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/registration/_id/index.vue

Fixed:
+900:Not getting registration question answer in registration detail view in registration question section .
+897:not getting success message for registration question from normal and recurring event.
+891:issue of label of delete toaster

bug_27:Fixed issue of question feeback not shown in registration detail view 

---

config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
pages/apps/_app/registration/_id/index.vue

Fixed:
+904:While editing the session when type is group then not getting tickets in ticket drop down
+900:Not getting registration question answer in registration detail view in registration question section

Fixed issue of multiple response UI issue and ticket dropdown not getting values everytime

---

assets/styles/main.css
config/templates/grids/eventRegistrationQuestion-grid/actions/row-select/edit-item.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json

Fixed:
+915: New and edit registration question form should be same check the form headings and top space
+814:badge ui is not looking good when we create new in mobile

Fixed issue of UI badge and toaster issue

---

assets/styles/main.css
components/common/help/index.vue
components/newRecurringEvent.vue
components/newSingleEvent.vue
pages/apps/_app/registration/_id/index.vue

#issue resolved 893
#some major issue solved

Dec issue 893

---

components/newSingleEvent.vue
nuxt.config.js

Fixed:
+898:While creating event , when there is error message on single event the save button should be disabled like recurring event
+880:while creating an event not getting any error message if user added numeric values in eventname and next button also not get enabled
+Added env variables to pick the values of siteId for the issue of login getting redirected to /dev instead of /admin

Fixed issue in login and 

---

assets/styles/main.css
components/common/grid/FieldsFilter.vue
config/templates/grids/eventInvites-grid/actions/grid/sendEventInvite.vue

#major issues fixes
#mobile issue fixes

Jan issue v1

---

assets/styles/main.css
components/common/grid/index.vue
config/apps/admin/content/badge.js
config/apps/event/content/eventcustomers.js
config/templates/grids/discountMember-grid/column-createddate.vue
config/templates/grids/eventTask-grid/actions/grid/new-item.vue
config/templates/grids/eventTask-grid/column-templateaction.vue
config/templates/grids/eventTask-grid/edit-surveytemplate.vue
config/templates/grids/eventTask-grid/edit-template.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json

Resolved issues #720,#927,#934,#858

Bug fixes jan v3

---

components/common/grid/FieldsFilter.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue

#resolved major issues
#resolved mobile isuue

Jan issue v3

---

components/common/grid/FieldsFilter.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/seatmap/_id/index.vue
store/index.js

Fixed:
+360:after close edit seatmap form should redirect to ticket section now redirecting to end of the page 
+232:In filter by default one section should be added and default value should be the placeholder as "" Select a field /Criteria

Bug_32:fixed issue of default filter value should not be deleted

---

assets/styles/main.css
components/common/form/select.vue
components/common/help/index.vue
components/newRecurringEvent.vue

#solved Mobile Issues
#solved major issues

Jan issue v4

---

components/common/upgrade/index.vue
config/templates/grids/organizationSubscription-grid/column-isactive.vue
layouts/admin.vue
layouts/default.vue
layouts/event.vue
layouts/integration.vue
layouts/seatmap.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json

Feat event upgrade

---

assets/styles/main.css
components/common/grid/index.vue
config/templates/grids/eventInvites-grid/actions/grid/sendEventInvite.vue
config/templates/grids/integrationapp-grid/body.vue
config/templates/grids/seatmap-grid/body.vue
pages/apps/_app/contacts/_id/index.vue

#mobile fixes
#solved major issues

Jan issue v5

---

pages/apps/_app/event/_id/index.vue

+946:Sometimes event tile or detail view page loads many time and shows attendee api failed with 404 (100:10)

fixed the issue of attendee api failing at random times

---

components/common/grid/index.vue
components/common/import/index.vue
config/common/templates/grid/actions/grid/export-csv.vue
pages/apps/_app/event/recurring/_id/index.vue

Jan issue v6

---

config/templates/grids/eventTickets-grid/actions/grid/new-item.vue
config/templates/grids/eventTickets-grid/actions/row-select/edit-item.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json

Fixed:
989:Ticket should accept the decimal points values also in ticket grid and create event form  (new/edit )
930:not getting success message after importing contacts from contact tab

Fixed issue of ticket money not taking decimal values

---

components/common/grid/index.vue
config/apps/event/rest/index.js
layouts/admin.vue
layouts/default.vue
layouts/event.vue
layouts/integration.vue
layouts/seatmap.vue

Bug fixes jan v6

---

api/index.js
nuxt.config.js
package.json
store/index.js
yarn.lock

Fixed:
1017:After logout application should take user to <user-org>-event.bitpod.io and not always to bitpod-event.bitpod.io

Bug logout issue

---

locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
middleware/authorization.js
pages/apps/_app/virtual/_id/index.vue

#video msg added
#session dynamic time added

Task video session

---

nuxt.config.js
pages/apps/_app/event/_id/editSiteSetting.vue

Fixed:
Issue in getting templates for wbcsd added a custom instance to add x-org-id

issue while fetching templates added x-org-id in the header

---

package.json

Added flag max-http-header-size and increased it up to 25kb

Header size issue with http request

---

assets/styles/main.css
layouts/event.vue
pages/apps/_app/organization/_id/index.vue

Jan issue 28

---

components/newRecurringEvent.vue
components/newSingleEvent.vue

Fixed
989:Ticket should accept the decimal points values also in ticket grid and create event form  (new/edit )

fixed issue of ticket price not accepting float values

---

assets/styles/main.css
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
middleware/authorization.js
pages/apps/_app/attendee/_id/index.vue
pages/apps/_app/contacts/_id/index.vue
pages/apps/_app/discountcodes/_id/index.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue
pages/apps/_app/organization/_id/index.vue

#issue fix of large screen
#lounge page issue fix

Jan issue 29

---

pages/apps/_app/virtual/_id/index.vue

Jan issue 29 2

---

components/common/grid/index.vue
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue

Resolved issues #1002, #added console debug for #851

Bug fixes jan v7

---

middleware/authorization.js
pages/apps/_app/event/_id/index.vue
pages/embed-cookie/index.vue
pages/forwardLogin/index.vue
pages/index.vue

Fixed:-
959:when we try to logout and try to login again then gives 400 error
1023:when we logout from free trial org and login again then sometimes not loads the eventboard data getting same issues on bitpod also for sometimes.
1036:even we login to app and try to open same url in another tab again its asking for login it should open event
1042:While login to event app with bitpod not loada the eventboard data sometimes, app stuck to this url " https://event.test.bitpod.io/admin/forwardLogin?targetDomain=bitpod "

login in different tab if the user is logged in

---

locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/embed-cookie/index.vue
pages/forwardLogin/index.vue
pages/get-started/index.vue

Updates the organization setup workflow to the new job based API.
- please perform squash merge.

Yash update org setup workflow

---

components/newRecurringEvent.vue
components/newSingleEvent.vue

Fixed:
+1034:when we login to event app and create event and publish but still publish button is showing on event details

Bug publish event button display

---

components/common/grid/index.vue
config/templates/grids/eventTask-grid/column-templateaction.vue

Resolved pagination issue and #970

Bug fixes feb v1

---

config/apps/list.js
package.json

Hotfix help center

---

components/common/form/lookup.vue
components/newRecurringEvent.vue
components/newSingleEvent.vue

adds `t-id` attribute to text-inputs type column in ticket section when creating new events.

configure test-id for lookups

---

assets/styles/main.css
pages/apps/_app/attendee/_id/index.vue
pages/apps/_app/organization/_id/index.vue

Feb issue v3 2

---

config/apps/event/content/contacts.js
config/templates/grids/integrationapp-grid/body.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/seatmap/_id/index.vue

Resolved issues #1056,#982,#1055

Bug fixes feb v3

---

locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/get-started/index.vue

- update orgAvailable to support unparsed similar to production

update get-started ui to be more consistent

---

config/templates/grids/eventTickets-grid/actions/grid/new-item.vue
config/templates/grids/eventTickets-grid/actions/row-select/edit-item.vue

Fixed:
1059:On add,edit ticket screen if we add paid ticket amount to 0.5 save button is not getting enable

Ticket price issue

---

pages/apps/_app/attendee/_id/index.vue
pages/apps/_app/virtual/_id/index.vue

Feb issue v4

---

pages/apps/_app/attendee/_id/index.vue

Feb issue 05

---

config/apps/event/gql/registration.gql
config/templates/grids/eventSession-grid/actions/form.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/registration/_id/index.vue

Bug fixes feb v4

---

components/common/grid/index.vue
components/newRecurringEvent.vue
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
config/templates/grids/eventSession-grid/actions/form.vue
nuxt.config.js

Resolved issues #1083, #1086, #1090

Bug fixes feb v5

---

config/templates/grids/livedraft-grid/body.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue
pages/apps/_app/organization/_id/index.vue

Changed contidition for view event url and added call to upload org log to cloudinary
Issue #1008
There are code changes in serve side Api -- uploadCloudinary 
Also registration site changes are deployed to test

Bug fixes feb v7

---

config/apps/list.js
config/templates/grids/discount-grid/column-ispercent.vue
config/templates/grids/eventTickets-grid/actions/row-select/edit-item.vue
pages/get-started/index.vue

Resolved issues #879, #1106, #1114, #1117

Bug fixes feb v9

---

pages/apps/_app/attendee/_id/index.vue

Feb issues v23

---

config/templates/grids/discount-grid/column-isactive.vue
config/templates/grids/discount-grid/column-ispercent.vue
config/templates/grids/eventTickets-grid/actions/row-select/edit-item.vue
pages/apps/_app/discountcodes/_id/index.vue

Resolved issues #1107,#1123,#1125

Bug fixes feb v10

---

assets/styles/main.css
pages/apps/_app/event/_id/editSiteSetting.vue

Fixed:
#1074:when i open reg page settings then first it shows small screen then loads skeleton

FIxed the issue of form card skeleton isssue

---

config/apps/help/index.js
config/apps/help/introduction.js
layouts/help-center.vue
nuxt.config.js
pages/apps/help-center/_section/_helpid/index.vue

- adds ability to configure swagger url via env variables

update swagger url logic

---

pages/apps/_app/eventboard/index.vue

Fixed:
1151:When i login to event app then on eventboard getting message as access not granted though i have an access and after refresh it works

Fixed issue of if user is having orgUser access then no access screen should be displayed

---

assets/styles/main.css
components/common/grid/index.vue
config/apps/event/gql/event.gql
config/templates/grids/livedraft-grid/body.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
package.json
pages/apps/_app/event/_id/index.vue
pages/apps/_app/virtual/_id/index.vue
yarn.lock

#fixes added for video player
#poster image added
#fix added for image

March issue v2

---

components/common/grid/index.vue
components/common/import/index.vue
config/common/templates/grid/actions/row-select/edit-item.vue
config/templates/grids/contact-grid/actions/grid/index.vue
config/templates/grids/eventAttendees-grid/actions/grid/index.vue
config/templates/grids/integrationapp-grid/body.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json

Resolved issues #1163,#1155,#1166,#1160,#1157 
In this PR if import jobs fails that implementation is remaining waiting for Adarsh fix will send it in next PR.

Bug fixes mar v4

---

assets/styles/main.css
config/templates/grids/registration-grid/actions/row-select/index.vue
config/templates/grids/registration-grid/actions/row-select/resendRegistrationEmail.vue
pages/apps/_app/eventboard/index.vue

FIxed:
#1161:Registration page settings form is not looking good, going out of screen on laptop
#1162:confirmation message popup  is not showing after resend registration email from registration grid 
#1088:When the event app is open from long time then sometimes getting message as "Access not granted, contact support to request access." whereas after refresh it works fine (random issue)
#1151:When i login to event app then on eventboard getting message as access not granted though i have an access and after refresh it works

Bug form UI fix

---

config/templates/grids/eventTickets-grid/actions/grid/new-item.vue
package.json

end date rename

---

config/apps/event/gql/eventAttendees.gql
config/templates/grids/eventAttendees-grid/actions/row-select/print-badges.vue
config/templates/grids/eventAttendees-grid/column-checkin.vue
config/templates/grids/registrationAttendees-grid/actions/row-select/print-badges.vue

Fixed:
1183:While printing the badeg not getting registration type color on attendee badge

Bug badge color code

---

assets/styles/main.css
config/templates/grids/eventTickets-grid/actions/grid/new-item.vue
config/templates/grids/registration-grid/actions/row-select/resendRegistrationEmail.vue
pages/apps/_app/event/_id/editEventForm.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/eventboard/index.vue

Fixed
1197:When i change the event end date and try to create new ticket or edit the ticket then on end date shows the "End date validation message"
1182:when we change end date of event created by get started route and try to create tickets with changed end date validations are showing
1151:When i login to event app then on eventboard getting message as access not granted though i have an access and after refresh it works
Linting issue

Bug ticket error msg

---

assets/styles/main.css
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue

#1201 resolved and banner image issue resolved

March issue v18

---

components/common/grid/index.vue

- respects hidden property in content.js

update desktop three dot logic

---

config/templates/grids/eventInvites-grid/actions/grid/sendEventInvite.vue
pages/apps/_app/event/recurring/_id/index.vue

Fixed:
1217:when we change any filed in send email invte and close form and if we open send email invite form again changes are still showing

Bug send email form clear

---

components/newRecurringEvent.vue

Fixed:
#1215:In the recurring event ticket quantity not getreduced though i purchase the ticket.
1211:when we add ticket whie create recurring event and added in session if we go back to tickets and delete one tickets and save the event deleted ticktes is showing in session grid

Bug recurring ticket count

---

pages/apps/_app/event/invite/_id/index.vue

added tooltip for invitee

---

config/templates/grids/livedraft-grid/body.vue
config/templates/grids/userRoles-grid/actions/row-select/delete-item.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/event/_id/editEventForm.vue
pages/apps/_app/event/_id/editEventSetting.vue
pages/apps/_app/event/_id/editSeoForm.vue
pages/apps/_app/event/_id/editSiteSetting.vue
pages/apps/_app/event/recurring/_id/index.vue
pages/apps/_app/organization/_id/editOrgInfoForm.vue
pages/apps/_app/organization/_id/editOrgSetting.vue
pages/apps/_app/organization/_id/editSocialMedia.vue
pages/apps/_app/organization/_id/editWorkTiming.vue
pages/apps/_app/organization/_id/index.vue

Fixed
#1231:When i delete the user getting message as "item deleted successfully" it should be "User deleted Successfully" and create user message should be "User created succesfully"
#1232:After editing org info, settings, social media and work timing from administration app, page is not getting refresh.
#1230:when we edit event details need to refresh data is not getting updated for recurring event.
#1206:On event tile view recurring events shows the "," though it does not have the address

Bug recurring refresh

---

components/newRecurringEvent.vue
components/newSingleEvent.vue
config/templates/grids/livedraft-grid/body.vue

Fixed
1190:While creating an event if the i select the paid type of ticket then default value of it should be 1
973:when user add the address then " , " should not be there after last word on admin and reg site also

Bug tile address

---

config/templates/grids/userRoles-grid/actions/grid/new-item.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/registration/_id/index.vue

Fixed:
#1241:Not getting the payment details in registration detail view when we make the paid payment
#1242:In registration detail view not getting full event address in event details section

Fixed issue of payment missing and address not getting displayed

---

assets/styles/main.css
config/templates/grids/userRoles-grid/actions/row-select/delete-item.vue
pages/apps/_app/event/invite/_id/index.vue

#issue resolved of grid
#tooltip issue resolved

March issue v25

---

components/newRecurringEvent.vue
pages/apps/_app/event/recurring/_id/index.vue

Fixed:
1211:when we add ticket while create recurring event and added in session if we go back to tickets and delete one tickets and save the event deleted tickets is showing in session grid 
1171:Reverted code for Live stream banner image displaying for recurring event which should not be.

Fixed issue of recurring ticket count

---

components/newRecurringEvent.vue
components/newSingleEvent.vue
pages/apps/_app/event/recurring/_id/index.vue

Fixed
1244:if I create recurring event and copy same event on click of back it should go to live and draft event not previous event
1190:While creating an event if the i select the paid type of ticket then default value of it should be 1.If updated then the ticket values are getting updated

Bug ticketprice change

---

nuxt.config.js
plugins/v-dialog.js
utility/index.js

Added v-dialog.js plugin and extended it to track form in google analytics
Added console debug to track for testing will remove once testing done

Extended v-dailog componet and added form tracking for google analytics

---

assets/styles/main.css
pages/apps/_app/attendee/_id/index.vue
pages/apps/_app/event/invite/_id/index.vue

#1168 Resolved
#1063 Resolved
#1257 Resolved

Apr issue v1

---

config/templates/grids/eventInvites-grid/actions/grid/sendEventInvite.vue
plugins/v-dialog.js

Resolved issue #1245, #1224, #1220 
For #1245, #1224 changes deployed in server side api
Also fixed the issue for the tabs in the forms are getting replaced with blank was facing issue on local

Bug fixws april v2

---

components/newSingleEvent.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/unsubscribe/index.vue

Fixed:
#1262:Check the font size of the Unsubscribe form it should be same as other forms
#1263:Check the success message font of unsubscribe page
#1261:While creating event when i click on back button and then not able to see the location details

added UI changes for unsuscribe form and fixed the clearing of form 

---

pages/apps/_app/attendee/_id/index.vue
pages/apps/_app/organization/_id/index.vue

Apr issues v5

---

config/templates/grids/livedraft-grid/body.vue

Fixed:
#973:when user add the address then " , " should not be there after last word on admin and reg site also

Fixed the address , issue

---

assets/styles/main.css
config/templates/grids/eventDiscountCode-grid/column-codetitle.vue
config/templates/grids/eventRegistrationQuestion-grid/column-controltype.vue
pages/apps/_app/attendee/_id/index.vue

clearInterval added
grid issue resolved

Apr issues v8

---

config/templates/grids/userRoles-grid/actions/grid/new-item.vue

Fixed
1258:When i delete the user and create new user then getting validation message on blank form

Fixed issue of form error not getting reset

---

assets/styles/main.css

Fixed
#1074:when i open reg page settings then first it shows small screen then loads skeleton

Bug form UI fix1

---

pages/apps/_app/event/_id/makeCopy.vue

Fixed:
1235:when i open the copy event form of normal event then first loads the recurring event form and then other details loads
Added a skeleton loader on form load

Bug address UI issue

---

nuxt.config.js
plugins/v-dialog.js
utility/index.js

commented the code for google analytics for pop-up forms use case

Bug fixes april v5

---

config/templates/grids/eventRegistrationForm-grid/actions/row-select/edit-item.vue
config/templates/grids/eventSession-grid/actions/form.vue
pages/apps/_app/event/_id/editSiteSetting.vue

Fixed:
#1293:On registration page settings the attached template should be selected, now shows the default template selected always
#1291:when we try to edit registration form in event detail view not able to save the details
#1288:While creating new session if i select the location type as venue and select the address from cache then location drop down remains stuck though i close the form

Bug google address dialog close

---

components/newRecurringEvent.vue
components/newSingleEvent.vue

- next button in new single and rec event
- phone rec event
- online rec event

add test ids to given fields

---

pages/apps/_app/virtual/_id/index.vue

#select 1st tile by default in video page
#live btn hide for now

Apr issues v22

---

config/templates/grids/eventInvites-grid/actions/grid/sendEventInvite.vue

Fixed:
#1273:When we save the email invite as draft , edit the drafted invites and saved it again then not getting new changes and even when we select the contact and then try to unselect it was getting failed and the past selected data was also getting cleared.-
Issue was as we are trying to edit the draft form the array which was containing the object was getting overwritten, so i have stored the data which i am getting as prefilled and then trying to store this already selected object back again to the object which was binded with the grid

Fixed issue on edit draft checkbox was not able to be deselected

---

components/newSingleEvent.vue
config/templates/grids/eventRegistrationQuestion-grid/actions/grid/new-item.vue
config/templates/grids/eventRegistrationQuestion-grid/actions/row-select/edit-item.vue
locales/en-US.json
locales/fr.json
locales/he.json
pages/apps/_app/event/_id/index.vue

- update ui in `New Single Event` form with recommendations from Neeraj:
- Improve spacing between `Add Tickets` Button and checkbox to disable tickets
- Rename `Add Tickets` button to `Add Ticket`.
- fix for `#1303` pass `context` to RegistrationQuestions grid.

Yash/update UI changes no ticket - 1303

---

layouts/default.vue

#added layout fixes for default layout

theme changes added for default layout

---

assets/styles/main.css
config/templates/grids/eventRegistrationQuestion-grid/actions/grid/new-item.vue
config/templates/grids/eventTask-grid/actions/grid/new-item.vue
layouts/admin.vue
layouts/default.vue
layouts/event.vue
layouts/help-center.vue
pages/apps/_app/organization/_id/index.vue

screen zoom issue for navigation resolved

Apr issues v28

---

components/common/form/date.vue
components/common/form/datetime-picker.vue
components/common/form/select.vue
components/newRecurringEvent.vue
components/newSingleEvent.vue
package.json
pages/apps/_app/event/recurring/_id/index.vue
yarn.lock

- also has minor fix for recurring event

fix tooltip for error in create new event 141 1312

---

pages/apps/_app/event/_id/index.vue

- hide show attendee form
- hide check for session conflict
- show allow cancellation

update event settings checkboxes - no ticket events

---

components/newSingleEvent.vue

- disables ticket toggle checkbox for new events on saving new event to prevent bugs during event creation process.

disable ticket toggle after new event save

---

config/apps/list.js
config/apps/member/content/index.js
config/apps/member/content/member.js
config/apps/member/gql/memberList.gql
config/templates/grids/contact-grid/column-0.vue
layouts/event.vue
layouts/member.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json

Task membership app

---

locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
package.json
pages/apps/_app/event/_id/editEventSetting.vue
yarn.lock

Fixed:
1054:When i create a ticket with decimal point in JPY currency, then from admin site its removing the pointed values and making it round figure but on registration site showing the same decimal values for ticket

Bug some currency not accepting decimal values

---

config/apps/list.js
layouts/member.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json

Membership app rename to community
app icon changed from app drawer

member app rename to community

---

config/templates/grids/contact-grid/actions/grid/invitationHistory.vue
config/templates/grids/eventInvitaionHistory-grid/column-0.vue
config/templates/grids/eventRegistrationType-grid/column-allowmultiple.vue
layouts/default.vue
layouts/member.vue

New member app route issue fixed
default layout loading issue fixed

May issues v4

---

config/apps/event/content/contacts.js
config/templates/grids/eventInvites-grid/actions/grid/sendEventInvite.vue

Fixed:
#1330:In community app while sending an email invite not getting prior invitations.

Fixed issue of not getting priorInvitee in the contact grid from member view

---

config/apps/member/content/index.js
pages/apps/_app/event/invite/_id/index.vue

Invites grid show issue resolved in member app

Member app bugs

---

config/templates/grids/eventIntegration-grid/freshbooks.vue
config/templates/grids/eventIntegration-grid/quickbooks.vue
config/templates/grids/eventIntegration-grid/xero.vue
config/templates/grids/integrationapp-grid/body.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
nuxt.config.js

feat: Re-connect the connection if the connection is expired in integration app
Server side changes in OrganizationInfo-getMyConnection api.

Feat integration re connect

---

nuxt.config.js

Reverted nuxt.config.js changes that was mistakenly merged by me in previous pull request

Reverted nuxt.config.js changes

---

layouts/admin.vue
layouts/event.vue

resolved drawer loading issue

---

config/apps/event/content/event.js
config/templates/grids/eventTask-grid/column-templateaction.vue
config/templates/grids/organizationTask-grid/actions/row-select/edit-item.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json

Fixed
#Changed the button-label 
#Changed the icon of edit scheduled type option
#Changed the column-order of the action

Bug btn label schedule task

---

components/common/grid/index.vue
config/apps/list.js
config/apps/member/content/member.js
config/apps/member/gql/memberList.gql
config/templates/grids/member-grid/body.vue
layouts/admin.vue
layouts/event.vue
layouts/member.vue

#added new view for member
#logo as per theme

Task member newview

---

components/common/grid/index.vue
pages/apps/_app/organization/_id/editOrgSetting.vue

#626 Event>>Search Event is working for selected page only
#623 Administration-->unable to edit the event registration url, even if it is not duplicate

Bug fixes may v2

---

layouts/member.vue
pages/apps/_app/attendee/_id/index.vue
pages/apps/_app/organization/_id/index.vue

#634 Resolved
#969,  #1313 Resolved

May issues v19

---

config/apps/member/content/feed.js

#640 Resolved

---

config/templates/grids/livedraft-grid/body.vue
pages/apps/_app/attendee/_id/index.vue

#628 Resolved
#642 Resolved
#616 Resolved (changes in all template, not needed PR or code changes)
for above issue changes in Templates

May issues v20

---

components/newRecurringEvent.vue
components/newSingleEvent.vue
config/apps/member/content/member.js
config/templates/grids/memberContacts-grid/actions/grid/add-existing-contacts.vue
config/templates/grids/memberSubscription-grid/actions/row-select/edit-item.vue
pages/apps/_app/event/_id/editSiteSetting.vue

Fixed:
#1349:When we try to setup the the reg. page setting's section heading then the label for venue section gets clear after save and doesnt reflect on reg site
#1316:2 recurrring events created while creating 1 recurring event
#617 :Not getting pagination on member card view from Community app
#639:Add Recurring event -Issues with creation of Rec event

Bug event reg page settings

---

Dockerfile

Updated the base image in dockerfile

updated base image

---

config/apps/event/content/event.js
config/templates/grids/integrationapp-grid/body.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/event/_id/editEventForm.vue
pages/apps/_app/event/_id/selectExistingSeatMap.vue
utility/rules.js

#658 : Edit Recurring event->Max registrations allowed is accepted as Negative value
#637 : Edit event=>Can save the event without Event Name, Organizer Name and organizer's email id
#598 : Existing Seat map could not selected
#597 : After setup connection, not getting three dots for non-auth connection from integration app

Resolved issues #658, #637, #598, #597

---

assets/styles/main.css
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/eventboard/index.vue

1. Eventboard is not looking good on black theme
2. Not able to see event title on event tile on black theme
3. Not able to see the form name 
4. RTE doesnt looks good not able to see the icons 
#610 Resolved

May issues v25

---

pages/get-started/index.vue
server-middleware/no-cache.js

- also updates error catch logic

add get-started page to not get cached 1319

---

components/common/grid/index.vue
components/common/theme/index.vue
layouts/default.vue
layouts/help-center.vue
layouts/integration.vue
locales/en-US.json
store/index.js
utility/index.js

#432 Resolved
#635 Resolved
#685 Resolved

May issue 432

---

config/templates/grids/memberContacts-grid/actions/grid/add-existing-contacts.vue
config/templates/grids/memberContacts-grid/actions/grid/new-item.vue
pages/apps/_app/contacts/_id/index.vue

#665 (Resolved)
#653 (Resolved)
#1340:In Community app from Contact detail view when i click on registration and click back arrow again then not getting contact details and loads all the registrations in reg grid

Fixed the UI fixes of existing member form and submit btn issue

---

pages/apps/_app/event/_id/print-ticket-management/index.vue

update view logic for ticket management view

---

utility/rules.js

Reverted changes for #682

---

pages/apps/_app/event/_id/index.vue

fix showing ticket grid 3 dot on no ticket event

---

config/apps/admin/content/lookup.js
config/apps/event/content/contacts.js
config/apps/event/content/event.js
config/apps/event/content/registrations.js
config/templates/grids/discount-grid/actions/form.vue
config/templates/grids/eventDiscountCode-grid/actions/grid/new-item.vue
config/templates/grids/eventDiscountCode-grid/actions/row-select/edit-item.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/organization/_id/editWorkTiming.vue

Resolved issues #624, #629, #732, #622, #615

Bug fixes may v9

---

config/apps/eSign/content/eSign.js
config/templates/grids/eSign-grid/ESignForm.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/eSign/_id/index.vue

- Fix search functionality in eSignature app to resolve #741
- Fix invalid status while data is loading to resolve #740

Fix search functionality and status while loading

---

components/common/recurringCalendar/index.vue

Fixed issue of not getting sessions in calender due to some object properties getting undefined

---

config/apps/event/content/event.js
config/templates/grids/eventSponsor-grid/actions/row-select/delete-item.vue
config/templates/grids/eventSponsor-grid/actions/row-select/edit-item.vue
layouts/admin.vue
layouts/default.vue
layouts/eSign.vue
layouts/event.vue
layouts/help-center.vue
layouts/integration.vue
layouts/live.vue
layouts/member.vue
layouts/public.vue
layouts/seatmap.vue
pages/apps/_app/event/recurring/_id/index.vue

#1315 Resolved (from sheet)
#739 (title added
#added sponsor edit custom form

Task sposor edit

---

config/apps/member/content/member.js
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
config/templates/grids/memberContacts-grid/actions/grid/add-existing-contacts.vue
config/templates/grids/memberContacts-grid/actions/grid/new-item.vue
config/templates/grids/memberContacts-grid/actions/row-select/delete-item.vue
pages/apps/_app/event/_id/editEventForm.vue

Fixed an issue of delete functionality in contact grid

---

pages/apps/_app/event-attendees/index.vue

Bug fixes may v10

---

config/templates/grids/eventSponsor-grid/actions/grid/new-item.vue
config/templates/grids/eventSponsor-grid/actions/row-select/edit-item.vue
config/templates/grids/livedraft-grid/body.vue
layouts/admin.vue
layouts/default.vue
layouts/eSign.vue
layouts/event.vue
layouts/help-center.vue
layouts/integration.vue
layouts/live.vue
layouts/member.vue
layouts/public.vue
layouts/seatmap.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
nuxt.config.js
pages/apps/_app/event/recurring/_id/index.vue
pages/apps/_app/member/_id/index.vue

#sponsor issue solved
#title added in Meta wrap in i18n
#742 Resolved

June issues v1

---

components/newSingleEvent.vue
config/apps/event/content/event.js
config/templates/grids/allEvents-grid/actions/row-select/edit-item.vue
config/templates/grids/eventSession-grid/actions/form.vue
config/templates/grids/integrationapp-grid/body.vue
pages/apps/_app/event/_id/editEventForm.vue

Resolved issues 
#591
#611
#752
#593
#609

Resolved issues #591, #611, #752, #593, #609

---

config/apps/event/content/contacts.js
config/apps/event/content/event.js
config/templates/grids/eventSponsor-grid/actions/grid/add-existing-contacts.vue

#751 Resolved
#contact view hide

Bug issue 751

---

config/apps/admin/gql/printedTickets.gql
config/templates/grids/printedtickets-grid/actions/grid/new-item.vue
pages/apps/_app/event/_id/print-ticket-management/index.vue
pages/apps/_app/organization/_id/editPrintedTicketTemplate.vue

- additional fixes to regression issues
- #705

Resolve random alert pop-up issue

---

config/templates/grids/eSign-grid/body.vue

- Remove the sample data provided while loading the esignature form

remove sample data provided

---

components/common/recurringCalendar/index.vue
components/newRecurringEvent.vue
config/templates/grids/eventInvites-grid/actions/grid/sendEventInvite.vue
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
layouts/admin.vue

#760 
#761 (Missed this in the last PR)

Fixed issue of dropdown not loading in recurring calender while logging with google

---

config/templates/grids/eventSponsor-grid/actions/row-select/delete-item.vue
layouts/admin.vue
layouts/default.vue
layouts/eSign.vue
layouts/event.vue
layouts/help-center.vue
layouts/integration.vue
layouts/member.vue
layouts/seatmap.vue

Bug issue 759

---

config/apps/member/content/member.js

Fixed issue of form validation of new member

---

components/common/recurringCalendar/index.vue

Fixed issue  of sessions not getting save

---

config/templates/grids/eventSponsor-grid/actions/grid/add-existing-contacts.vue

#751 Resolved getting issue for login with google

June issue v4

---

config/templates/grids/eventInvites-grid/actions/grid/sendEventInvite.vue
config/templates/grids/eventSession-grid/actions/form.vue
plugins/apollo-error-handler.js
utility/index.js

#751 
Dependency error of login

Fixed issue of gql throwing variant flight query error and trying to reset the store in the middle of the query executing

---

nuxt.config.js
pages/apps/_app/eSign/index.vue

feat: update signature url

---

components/common/grid/index.vue
config/templates/grids/feed-grid/body.vue

June issue v813

---

assets/styles/main.css
components/common/grid/core-grid.vue
components/common/grid/index.vue
components/common/grid/observer.vue
config/templates/grids/connectedApps-grid/column-action.vue
pages/apps/_app/event/_id/index.vue

feat lazy loading grids

---

config/templates/grids/eSign-grid/ESignForm.vue
pages/apps/_app/eSign/_id/index.vue

- Resolve issue #770
- Resolve issue #779
- Resolve issue #780

Fix eSignature form validation and add confirmation messages

---

pages/myRegistration/_id/index.vue

Resolved issues #857 resolved in templates
#856 
#853 server side changes

Resolved issue #856

---

config/apps/event/gql/registration.gql
pages/apps/_app/registration/_id/index.vue

Changes regarding to display transaction id on registration detail view

Changes regarding transaction id

---

config/templates/grids/eventIntegration-grid/paytmbusiness.vue

Changes for PayTMBusiness integration form

Changes for paytm integration form

---

components/common/grid/observer.vue
components/common/scanner/index.vue

Fix relevant attendee name on checkin

---

config/templates/grids/organizationBussinessUnit-grid/actions/form.vue
config/templates/grids/organizationBussinessUnit-grid/actions/grid/new-item.vue
config/templates/grids/organizationBussinessUnit-grid/actions/row-select/edit-item.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json

Bug fixes june v8

---

pages/myRegistration/index.vue

updated error message location when registration not found

updated error message when registration not found

---

config/templates/grids/eventIntegration-grid/braintree.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
utility/rules.js

Resolved issue #888
Braintree integration form changes

Resolved issue #888 and Braintree integration form changes

---

components/common/footer/index.vue
config/templates/grids/livedraft-grid/body.vue
pages/apps/_app/event/recurring/_id/index.vue
pages/myRegistration/index.vue

June issue 893

---

pages/apps/_app/user-profile/deleteUserAccount.vue
pages/apps/_app/user-profile/editUserProfileInfo.vue
pages/apps/_app/user-profile/index.vue
pages/get-started/index.vue

Fixed:-
#901 
#900
#849
#844
#614

Fixed the issue of delete functionality not getting the error message

---

config/templates/grids/eventIntegration-grid/braintree.vue
config/templates/grids/eventIntegration-grid/paytmbusiness.vue
package.json

Resolved issues for integration form changes
Version update for patch release

Patch release payment gateway 30 june2021

---

config/templates/grids/eventIntegration-grid/braintree.vue
config/templates/grids/eventIntegration-grid/paytmbusiness.vue
package.json

Sync_release_branch with current rls_03-06-2021

Sync_release_branch with current rls_03-06-2021

---

components/common/app-logo/index.vue
layouts/admin.vue
layouts/default.vue
layouts/eSign.vue
layouts/event.vue
layouts/member.vue
layouts/seatmap.vue

June issue v855

---

components/common/app-drawer/index.vue
config/templates/grids/allEvents-grid/actions/row-select/edit-item.vue
config/templates/grids/eventAttendees-grid/column-checkin.vue
config/templates/grids/registrationAttendees-grid/column-checkin.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue

Fixed:
#838 
#876
#815
#643
#832

Bug checkin disabling

---

config/apps/event/content/contacts.js
config/apps/event/content/event.js
config/apps/event/content/eventcustomers.js
config/apps/event/content/registrations.js
config/templates/grids/allEvents-grid/actions/row-select/edit-item.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/event/_id/editEventForm.vue
utility/index.js

Resolved issues 
#811 
#591 
#927 -- server side changes in eventRegister api
#912

Resolved issue #811, #591

---

utility/rules.js

Resolved issue #811 
#600 --server side changes

Resolved issue #811

---

config/apps/event/gql/eventRecurringSession.gql
config/apps/event/gql/location.gql
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue

Bug july fixes 3

---

assets/styles/main.css
config/apps/admin/content/lookup.js
config/apps/event/content/contacts.js
config/templates/grids/eventSponsor-grid/actions/grid/add-existing-contacts.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
pages/apps/_app/attendee/_id/index.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue
pages/apps/_app/organization/lookups/index.vue

#939 Resolved
#929 Resolved for Recc event
#794 Added
#635 Resolved
#798 Resolved

July issue v5

---

config/apps/event/content/event.js
config/apps/member/content/member.js
pages/apps/_app/event/_id/index.vue

Fixed the 3 dot display issue in bitpod virtual event

---

assets/styles/main.css
components/common/app-logo/index.vue
config/apps/event/content/event.js
config/templates/grids/eventSponsor-grid/actions/row-select/delete-item.vue
layouts/admin.vue

#828 Resolved
#884 Resolved
#796 Resolved
#941 Resolved

July issue v6

---

components/newRecurringEvent.vue
config/templates/grids/eventAttendees-grid/column-checkin.vue
config/templates/grids/eventRecurringSession-grid/actions/grid/new-item.vue
config/templates/grids/eventRegistrationQuestion-grid/actions/row-select/delete-item.vue
config/templates/grids/eventSponsor-grid/actions/row-select/delete-item.vue
config/templates/grids/eventTickets-grid/actions/row-select/delete-item.vue
config/templates/grids/registrationAttendees-grid/column-checkin.vue
locales/en-US.json
pages/apps/_app/event/_id/index.vue

Fixed:
#812 
#876
#Resolved the dependent issue of delete multiple tickets not working.
#Found a test case  in create recurring event which was failing fixed it

fixed issue of multiple deletes not working

---

components/common/grid/core-grid.vue
components/newRecurringEvent.vue
config/apps/admin/content/lookup.js
utility/index.js

Fixed issue of add existing contact not working and field validation not working in default forms

---

components/common/form/file.vue
utility/index.js

Resolved issue #603

---

assets/styles/main.css
config/templates/grids/eventRegistrationQuestion-grid/actions/grid/new-item.vue
pages/apps/_app/event/_id/index.vue
pages/apps/_app/event/recurring/_id/index.vue

July issue v13

---

pages/apps/_app/event-attendees/_id/index.vue
pages/apps/_app/event/_id/index.vue

Resolved issue #852

---

config/templates/grids/userprofile-grid/column-timestamp.vue
package.json
yarn.lock

Bug july fixes 8

---

components/common/form/file.vue
utility/index.js

Bug fixes july v4

---

config/apps/event/content/event.js

added a function through which i can pass the filter to get the data in a sorted way

---

components/common/user-profile/index.vue
config/apps/list.js
layouts/admin.vue
layouts/eSign.vue
layouts/event.vue
layouts/help-center.vue
layouts/integration.vue
layouts/member.vue
layouts/seatmap.vue
layouts/user-profile.vue

Added the userprofile section inside the user icon pull out option

Bug userprofile env issue

---

components/common/app-drawer/index.vue
config/apps/list.js

Fixed:
Found a dependency issue throwing unauthorized when clicking user-profile

added list of apps
