bitpodio/bitpodjs

components/common/grid/index.vue
config/common/templates/grid/actions/grid/index.vue
config/common/templates/grid/actions/row-select/index.vue

1. add REST grid refresh action which can be used in New Item, edit Item, delete Item custom forms
2. refresh is available on grid & row-select actions forms.

Add REST grid refresh action for CRUD forms 

---

config/templates/grids/allEvents-grid/actions/row-select/edit-item.vue
config/templates/grids/livedraft-grid/body.vue
config/templates/grids/registrationAttendees-grid/column-checkin.vue
locales/en-US.json
pages/apps/_app/event/_id/editEventForm.vue
pages/apps/_app/event/recurring/_id/index.vue
pages/apps/_app/registration/_id/index.vue

Fixed:
+676:if we delete any draft event confirmation message should be " Event deleted Successfully "
+added delete recurring draft event functionality from the tiles
+672:when we edit the event name from tile edit option then not reflect the changes on tile until we refresh the page 
+669:In registration detail view added the chip to the status of registration
+663:For some events getting two banner image image attached to it
+622:remove check in option for failed registration from the registration attendee grid

Bug 18 banner issue

---

pages/apps/_app/organization/_id/index.vue

- limits width of text element to 125px in image gallery to prevent irregular sizing of image cards and bring `.text-truncate` into effect.

fix text overflow due to file name len org gallery (711)

---

components/common/form/timezone/index.vue
components/newRecurringEvent.vue

This is a partial fix and will require the following fixes:
`Issue present on tablet resolution when scrolling horizontally.`
Possible fix that comes to mind:
- Disable scrolling of content when pop-up is open.

fix autocomplete dropdown not attaching 434

---

components/common/grid/index.vue

This is a patch to the fix applied in #213.
limit overflow-y hidden to mobile resolution:
- only apply when div has role of menu

limit overflow-y hidden to mobile resolution

---

pages/apps/_app/event/_id/newBadgeForm.vue

Fixed:
+856:when we close create new badge form then also shows success message as event updated successfully

bug_26:badge toaster get triggered on closing the form

---

components/common/grid/index.vue

- adds a `key` to the `v-data-table`.
- When the `key` value gets updated, it indicates to Vue that it should re-render the component.
- The component should be rendered with the correct slot.

force data table rerender on body slot

---

components/newRecurringEvent.vue
components/newSingleEvent.vue
config/templates/grids/eventInvites-grid/actions/grid/sendEventInvite.vue
config/templates/grids/eventRegistrationForm-grid/actions/row-select/edit-item.vue
config/templates/grids/eventRegistrationType-grid/column-isdefault.vue
config/templates/grids/eventSession-grid/actions/form.vue
config/templates/grids/eventTask-grid/edit-surveytemplate.vue
locales/en-US.json
locales/fr.json
locales/he.json
locales/hi-IN.json
utility/rules.js

+920:after creating and editing the session message should be like session created /edited successfully
+921:check the edit registration form top space and success message should be like "Registration form updated successfully" Not fixed
+901:Location not getting in calendar invite for bitpod virtual type recurring event 
+905:while sending an email invite from contact scroll should set to top when i change the tab
+868:not getting survey email template while editing template (Random Issues)
+880:while creating an event not getting any error message if user added numeric values in eventname and next button also not get enabled 
+898:While creating event , when there is error message on single event the save button should be disabled like recurring event

Fixed issue of invitee survey template

---

pages/apps/_app/eventboard/index.vue

- fixes flash of event is empty message instead of skeleton when the eventboard is loading.

add more logic to decide events on sale is empty

---

components/common/grid/index.vue
config/templates/grids/eventRegistrations-grid/actions/row-select/index.vue
config/templates/grids/eventRegistrations-grid/actions/row-select/resendRegistrationEmail.vue
pages/apps/_app/event/_id/index.vue

This PR also adds the following functionality:
- The `confirm` dialog has been moved to the  `common/grid` component. In order to use the component, the event `toggle-confirm` needs to be called:
- It requires the following parameters to be passed with it:
- `this.viewName | String` - name of the view for which it toggles
- `callback | String` - name of event to emit on successful confirmation
- `options | Object` - standard options for the confirm dialog, contains a `title | String` value, `message | String` value and `options | Object`. Ref. to `components/Confirm.vue`.
-  The `snackbar` component has also had functionality added to be toggled via eventbus in the `common/grid`, the event is `toggle-snackbar`.
- It requires the following parameters to be passed with it:
- `this.viewName …

add logic to move rowselect to triple dot on desktop 933 62

---

components/common/grid/index.vue

Remove caching from graphql requests for csv export to prevent exporting wrong data

update graphql query to not cache

---

components/common/form/file.vue

Fixed:
1058:banner image is not getting attached  when we delete it and try to add same image

fixed issue of unable to upload same banner image file

---

config/apps/event/content/event.js

Fixed:
1205:when we edit recurring event name and save the changes event get removed from events

Fixed issue of recurring event not getting displayed

---

layouts/admin.vue
layouts/event.vue
layouts/help-center.vue
layouts/integration.vue
layouts/seatmap.vue
nuxt.config.js
server-middleware/no-cache.js

- prevents `/eventboard` from being cached and prevent `auth` check on back button.

add no-cache server middleware 1187

---

config/common/templates/grid/actions/row-select/edit-item.vue

Fixed:
1238:When i edit the contact or registration from grid then automatically created date gets change

Fixed issue of created date getting modified when trying to edit in default grid

---

pages/apps/_app/event/_id/editSiteSetting.vue

Fixed:
1283 :on registration page getting old event template

Fixed issue of default template getting wrong name saved

---

components/common/grid/index.vue
pages/apps/_app/event/_id/index.vue

- Found out that the parameter from old event got cached which caused them to be supplied to props for new grids momentarily before new data is fetched and updated. Adding a watcher to the prop allowed to update the data once new values are sent via props.
- also updates logic for how keys are assigned to data tables, further improvements for `#62`.

update no message logic to avoid wrong messages

---

components/common/grid/index.vue
config/templates/grids/eventInvites-grid/actions/grid/sendEventInvite.vue

Fixed:
1296:Fixed the UI of the preInvitee form
1297:Not able to select the prior invite second time while sending an email invite from event detail view-The problem with this issue was that when user was trying to reset the preinvitee form dialog data but on reset the grid was not able to know that the data was reset and the grid must reset the selected data.So i tried to emit an event which have been used to reset the grid data.

added code to emit the grid clear on clicking the resetButton

---

components/common/grid/index.vue
components/newRecurringEvent.vue
config/templates/grids/allEvents-grid/actions/row-select/edit-item.vue
config/templates/grids/eventInvites-grid/actions/grid/sendEventInvite.vue
config/templates/grids/eventInvites-grid/actions/grid/test4.html
layouts/default.vue

Fixed:
#1320:when we edit the event from all events view confermation message is not showing on save
#1311:The google meet and zoom warning message should get clear when i select the bitpod virtual meet as a location type
#1306:From send email invite when i try to clear advanced filter then selected contacts are also get cleard (related 1297)
#1297:Not able to select the prior invite second time while sending an email invite from event detail view
#1273:Not getting selected prior invite after editing the draft mail(Reopen)-This was not saving the parentId while creating the draft mail due to which the while editing it was not showing the draft prior invitee

Bug send event invitee preinvitee

---

config/templates/grids/eventRegistrationType-grid/column-allowmultiple.vue

Fixed:
1323:From edit registration type form if i check or uncheck the allow multiple checkbox then not reflecting to the grid-
On opening the dialog and then saving the form with isMultiple set to true was not getting updated properly. So added a watcher to the object key and updating it on change of the object value

Bug reg type isMutiple checkbox on select not getting updated 

---

config/common/templates/grid/error.vue
nuxt.config.js
plugins/apollo-error-handler.js
utility/index.js

Fixed issue of google login and also if you keep the screen in standby mode the gql query was getting failed which led to the msg "Session expired".
Have gone through the docs:- https://www.npmjs.com/package/@nuxtjs/apollo. Found out the various options through we could inject the error and handle it.Found a option in it using error handler and making a plugin which is handling this bypass of error if there is any in gql there i am setting the token now with new token.

Bug token refresh issue

---

components/common/grid/index.vue
config/apps/event/content/contacts.js
config/apps/event/content/event.js
config/templates/grids/eventInvites-grid/actions/grid/sendEventInvite.vue
pages/apps/_app/event/invite/_id/index.vue

Fixed:
1339:When I edit the draft email invite from community tab then getting only one prior invitation
1329:When the user edit the draft email and try to select prior invite then getting calendar invitation and registration mails
1328:When I try to edit the draft email invite second time and save then it get removed from invitation history

Fixed issue of sendEmail invite not able to select mutiple prior invitee
